tut5: restructuring
post-layout sim has a couple of wierd errors

1.
Circuit: ** sch_path: /home/ee24s053/ee5311-2025/tut5/inv/sim/post-layout/delay.sch

Error on line 1137 or its substitute:
  m.x1.x0.msky130_fd_pr__pfet_01v8 vout x1.in.t0 vin vin x1.x0:pshort_model l=    0.000000000000000e+00     w=    0.000000000000000e+00     ad=    2.520000000000000e-01     as=    2.520000000000000e-01     pd=    2.280000000000000e+00     ps=    2.280000000000000e+00     nrd=                      inf     nrs=                      inf     sa=    0.000000000000000e+00     sb=    0.000000000000000e+00     sd=    0.000000000000000e+00     nf=    1.000000000000000e+00     delvto=                     -nan
could not find a valid modelname
    Simulation interrupted due to error

2.
ERROR: /home/ee24s053/.klayout/pymacros/run_magic_extract.lym:52: AttributeError: 'NoneType' object has no attribute 'split'
  /home/ee24s053/.klayout/pymacros/run_magic_extract.lym:52

Signed-off-by: Karthik B K <ee24s053@smail.iitm.ac.in>