tut5: prep complete
inv layout drc/lvs clean
sim errors exist post-layout

"""
Error: Mismatch of .subckt ... .ends statements!
    in file /home/ee24s053/ee5311-2025/tut5/inv/prim/inv_extracted.spice
    This will cause subsequent errors.

Check .ends in line number
"""

Signed-off-by: Karthik B K <ee24s053@smail.iitm.ac.in>